### ISSUE TITLE
Cannot use the visualizer in VS2019 Enterprise 16.3.5

### ISSUE THREAD

**Issue by xuzhg** [zspitz/ExpressionToString#96]
**Describe the bug**  
I got the following error dialog:

![image](https://user-images.githubusercontent.com/9426627/67155527-1fa71200-f2c6-11e9-900c-0f906a2b93dd.png)

**To Reproduce**  

1. Debug an Unit test
2. Stop on Expression

3. Click:

![image](https://user-images.githubusercontent.com/9426627/67155541-42392b00-f2c6-11e9-8359-bc1d313f9662.png)

4. Got the error dialog

**Comment by zspitz** [comment]
@xuzhg @Matt500b I'm sorry for the delay; I've been unavailable for the past few days.

1. What version of Visual Studio are you using? 
2. Is this a .NET Framework project, or a .NET Core project? What version or versions is the project targeting?

**Comment by xuzhg** [comment]
@zspitz Thanks for response.

Actually, I resolved my Expression problem. But i can share the detail about using the visualizer.

For the VS version, it's listed on the title: VS2019 Enterprise 16.3.5

For the project, my lib is .NetStandard 2.0, my test project is .netcoreapp 2.0.

**Comment by zspitz** [comment]
@xuzhg I'll test and get back to you.

**Comment by zspitz** [comment]
@xuzhg Is the file [unblocked](https://github.com/zspitz/ExpressionToString/wiki/Troubleshooting-visualizer-installation)?

**Comment by xuzhg** [comment]
@zspitz No, I did not unblock it. Let me try later.

**Comment by xuzhg** [comment]
@zspitz It works.

I put the unblocked dlls into the following folders, meanwhile i created a subfolder named "netstandard2.0" and copy the dlls into this folder too.

![image](https://user-images.githubusercontent.com/9426627/67456284-1e872500-f5e5-11e9-8f18-6324a6011e38.png)

**Comment by zspitz** [comment]
@xuzhg Thanks.

Closing as related to unblocked files.
